### ISSUE TITLE
user config workflow should be more clear

### ISSUE THREAD

**Issue by 99alfie** [TrixterFilm/trackteroid#68]
# Problem Statement
According to the docs, two files have to be created - `trackteroid_user_config.py` and `trackteroid_relationships.json`, but it does not state where to put them and where to import/call them. The `RELATIONSHIPS_RESOLVER` is being called in two places - `trackteroid.query.__init__` and trackteroid.query.query`, which is confusing - one of them should be removed.
With a bit of digging, all this information can be concluded from the code but that is time consuming and an inconvenience for the user.

# Expected Behavior
To avoid the user having to find where to place the user files and how to hook them in without diving into the code, the user files could be included in an empty form / containing the default `RELATIONSHIPS_RESOLVER` from configuration.py (where it can be removed). The `RELATIONSHIPS_RESOLVER` is then created in one place only and is called only once. The docs can then point to these files directly and all the user has to do is copy/paste the example and all is working.

**Comment by rkoschmitzky** [comment]
The documentation is pretty clear about that a custom config python file can be put anywhere.
![image](https://github.com/TrixterFilm/trackteroid/assets/25324713/98d008a0-ee62-40cf-881d-46b7c5b0fd85)

There is no requirement to have a separate .json file for relationships. As stated in the docs 
> Here’s an example implementation of a custom resolver in a trackteroid_user_config.py file.

this is only one example, of how to externalize relationships and source them conditionally.

It is also intentional that the internal configuration.py is not an example the user should copy from. Please note that the internal configuration has some [fallback concepts ](https://github.com/TrixterFilm/trackteroid/blob/main/src/trackteroid/configuration.py#L120)in case of misconfiguration and unexpected issues on the user end. The expected datatypes and schemas should be explained in the docs though.

> The RELATIONSHIPS_RESOLVER is being called in two places - trackteroid.query.__init__ and trackteroid.query.query`, which is confusing - one of them should be removed.

Can you elaborate a bit more on this point? Why would the places where a resolver is being called from within the API would be important to know from the user's perspective?

**Comment by rkoschmitzky** [comment]
Can we create a different label for documentation/workflow improvement for those kind of tickets?

**Comment by 99alfie** [comment]
> 

I changed the label to "documentation".

**Comment by 99alfie** [comment]
I was trying to implement the user file(s) without the environment variable. Sorry did not mention that. When using the env var, all is working as expected. I remember we discussed the implementation but trying it out now makes me object to a few points here:

Here are my objections to this approach:
- it requires two configuration files instead of just one which adds complexity
- it requires a .py file containing imperative code and a separate json file (or database etc.) to contain the declarative code. From a design standpoint, the imperative code should remain with the codebase and there is no need to separate it out. As of the data part (json etc.), this could be anywhere of course
- while the env var is convenient, it currently is the only way
- while it is a good idea having potential differences of dictionary structure in future apis and preparing for that, it is not right now necessary and required, adding complexity that could be added when required

I believe it would be more convenient to have a default configuration containing the relationships resolver as a class, which can be derived from, but in the codebase.

The example would then explain implementing your own resolver and the optional json file. In this case, only one external file (and only declarative) would exist in the json example, and the env var to the .py file would be redundant.

An env var pointing to the json file could be implemented in the json example instead, so the path is not hardcoded in the .py file.

**Comment by 99alfie** [comment]
>Can you elaborate a bit more on this point? Why would the places where a resolver is being called from within the API would be important to know from the user's perspective?

```from ..configuration import RELATIONSHIPS_RESOLVER```

is called in both files - this was important for me as I was not using the TRACKTEROID_CONFIGURATION env var

**Comment by rkoschmitzky** [comment]
> I was trying to implement the user file(s) without the environment variable. Sorry did not mention that. When using the env var, all is working as expected. I remember we discussed the implementation but trying it out now makes me object to a few points here:
> 
> Here are my objections to this approach:
> 
> * it requires two configuration files instead of just one which adds complexity

For the user, there is only one configuration file mandatory. Everything else is in the hands of the user who is integrating Trackteroid.

> * it requires a .py file containing imperative code and a separate json file (or database etc.) to contain the declarative code. From a design standpoint, the imperative code should remain with the codebase and there is no need to separate it out. As of the data part (json etc.), this could be anywhere of course

Json is only one approach of many how a user might want specific relationships. There might be different integrations, like getting this information from a proper database or Ftrack itself. A Python configuration file is not uncommon (Sphinx does it also via Python), and it is not only meant to contain static data. You might want to use third-party packages to do a particular job.

There are and potentially will be other settings like the `ALLOWED_FOR_DELETION_RESOLVER` that need to be very dynamic, you might want to define this on a per user and perform regex matches. 
Our API should not dictate to the user how to do resolutions, but just provide the hooks to do it in a flexible and reasonably convenient way.

> * while the env var is convenient, it currently is the only way

That is exactly why a Python configuration shines - only one config that is flexible enough.

> * while it is a good idea having potential differences of dictionary structure in future apis and preparing for that, it is not right now necessary and required, adding complexity that could be added when required
> 
> I believe it would be more convenient to have a default configuration containing the relationships resolver as a class, which can be derived from, but in the codebase.

How would that custom resolver subclass then be configured for trackteroid? From the usage perspective within a Query initialization, it would be pretty much the same with the addition that you have to add your custom resolver implementation being part of the PYTHONPATH or any other custom envvar. To me, there isn't a real difference with the exception that Tractkeroid would not only have to specify a valid schema but also needs to provide a proper implementation interface. I think this overcomplicates things.

> 
> The example would then explain implementing your own resolver and the optional json file. In this case, only one external file (and only declarative) would exist in the json example, and the env var to the .py file would be redundant.
> 
> An env var pointing to the json file could be implemented in the json example instead, so the path is not hardcoded in the .py file.

I think my previous answers should already express my concerns regarding this suggestion. 

I hope everything makes sense to you and clarifies the taken approach well enough. Maybe you can express a bit more what currently feels inconvenient or isn't clear enough from the documentation.

**Comment by 99alfie** [comment]
Ok it makes more sense to me now, thank you
